ALTER TABLE RATING
	DROP
		CONSTRAINT FK_MOVIE_TO_RATING
		CASCADE;

ALTER TABLE RATING
	DROP
		CONSTRAINT FK_MEMBER_TO_RATING
		CASCADE;

ALTER TABLE GENRE
	DROP
		CONSTRAINT FK_MOVIE_TO_GENRE
		CASCADE;

ALTER TABLE MOVIETIME
	DROP
		CONSTRAINT FK_SCREEN_TO_MOVIETIME
		CASCADE;

ALTER TABLE MOVIETIME
	DROP
		CONSTRAINT FK_MOVIE_CINEMA_TO_MOVIETIME
		CASCADE;

ALTER TABLE BOOKING
	DROP
		CONSTRAINT FK_MEMBER_TO_BOOKING
		CASCADE;

ALTER TABLE BOOKING
	DROP
		CONSTRAINT FK_NONMEMBER_TO_BOOKING
		CASCADE;

ALTER TABLE BOOKING
	DROP
		CONSTRAINT FK_MOVIETIME_TO_BOOKING
		CASCADE;

ALTER TABLE BOOKING
	DROP
		CONSTRAINT FK_MOVIE_CINEMA_TO_BOOKING
		CASCADE;

ALTER TABLE SEAT
	DROP
		CONSTRAINT FK_SCREEN_TO_SEAT
		CASCADE;

ALTER TABLE MOVIE_CINEMA
	DROP
		CONSTRAINT FK_MOVIE_TO_MOVIE_CINEMA
		CASCADE;

ALTER TABLE MOVIE_CINEMA
	DROP
		CONSTRAINT FK_SCREEN_TO_MOVIE_CINEMA
		CASCADE;

ALTER TABLE SCREEN
	DROP
		CONSTRAINT FK_CINEMA_TO_SCREEN
		CASCADE;

ALTER TABLE BOOKING_SEAT
	DROP
		CONSTRAINT FK_BOOKING_TO_BOOKING_SEAT
		CASCADE;

ALTER TABLE BOOKING_SEAT
	DROP
		CONSTRAINT FK_SEAT_TO_BOOKING_SEAT
		CASCADE;

ALTER TABLE BOARD
	DROP
		CONSTRAINT FK_MEMBER_TO_BOARD
		CASCADE;

ALTER TABLE MEMBER
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE RATING
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE GENRE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE MOVIE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE MOVIETIME
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE CINEMA
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE BOOKING
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE SEAT
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE MOVIE_CINEMA
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE SCREEN
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE BOOKING_SEAT
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE BOARD
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

/* 회원 */
DROP TABLE MEMBER 
	CASCADE CONSTRAINTS;

/* 평점 */
DROP TABLE RATING 
	CASCADE CONSTRAINTS;

/* 장르 */
DROP TABLE GENRE 
	CASCADE CONSTRAINTS;

/* 영화 */
DROP TABLE MOVIE 
	CASCADE CONSTRAINTS;

/* 영화시간 */
DROP TABLE MOVIETIME 
	CASCADE CONSTRAINTS;

/* 영화관 */
DROP TABLE CINEMA 
	CASCADE CONSTRAINTS;

/* 예매 */
DROP TABLE BOOKING 
	CASCADE CONSTRAINTS;

/* 좌석 */
DROP TABLE SEAT 
	CASCADE CONSTRAINTS;

/* 영화_영화관 */
DROP TABLE MOVIE_CINEMA 
	CASCADE CONSTRAINTS;

/* 스크린 */
DROP TABLE SCREEN 
	CASCADE CONSTRAINTS;

/* 예매_좌석 */
DROP TABLE BOOKING_SEAT 
	CASCADE CONSTRAINTS;

/* 게시판 */
DROP TABLE BOARD 
	CASCADE CONSTRAINTS;

/* 회원 */
CREATE TABLE MEMBER (
	MEMBERNO NUMBER NOT NULL, /* 회원번호 */
	ID VARCHAR2(2000), /* 아이디 */
	PW VARCHAR2(2000), /* 비밀번호 */
	NAME VARCHAR2(2000), /* 이름 */
	SEX VARCHAR2(2000), /* 성별 */
	BIRTH DATE, /* 생년월일 */
	ADDR VARCHAR2(2000), /* 주소 */
	TEL VARCHAR2(2000), /* 전화번호 */
	EMAIL VARCHAR2(2000) /* 이메일 */
);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			MEMBERNO
		);

/* 평점 */
CREATE TABLE RATING (
	RATINGNO NUMBER NOT NULL, /* 평점번호 */
	MOVIECD NUMBER, /* 영화코드 */
	RATING NUMBER, /* 평점 */
	TIMESTAMP TIMESTAMP(3), /* 시간 */
	MEMBERNO NUMBER /* 회원번호 */
);

ALTER TABLE RATING
	ADD
		CONSTRAINT PK_RATING
		PRIMARY KEY (
			RATINGNO
		);

/* 장르 */
CREATE TABLE GENRE (
	GENRENO NUMBER NOT NULL, /* 장르번호 */
	GENRENAME VARCHAR2(2000) NOT NULL, /* 장르이름 */
	MOVIECD NUMBER /* 영화코드 */
);

ALTER TABLE GENRE
	ADD
		CONSTRAINT PK_GENRE
		PRIMARY KEY (
			GENRENO
		);

/* 영화 */
CREATE TABLE MOVIE (
	MOVIECD NUMBER NOT NULL, /* 영화코드 */
	TITLE VARCHAR2(2000) NOT NULL, /* 영화명 */
	TITLEEN VARCHAR2(2000), /* 영화명(영문) */
	YEAR NUMBER, /* 제작연도 */
	NATION VARCHAR2(2000), /* 제작국가 */
	TYPE VARCHAR2(2000), /* 유형 */
	GENRE VARCHAR2(2000), /* 장르 */
	DIRECTOR VARCHAR2(2000), /* 감독 */
	COMPANY VARCHAR2(2000), /* 제작사 */
	OPENDATE VARCHAR2(2000), /* 개봉일 */
	RUNNINGTIME VARCHAR2(2000) /* 상영시간 */
);

ALTER TABLE MOVIE
	ADD
		CONSTRAINT PK_MOVIE
		PRIMARY KEY (
			MOVIECD
		);

/* 영화시간 */
CREATE TABLE MOVIETIME (
	TIMENO NUMBER NOT NULL, /* 시간번호 */
	S_DATE DATE NOT NULL, /* 개봉일 */
	E_DATE DATE, /* 종료일 */
	STARTTIME VARCHAR2(2000) NOT NULL, /* 시작시간 */
	COUNT NUMBER NOT NULL, /* 상영회차 */
	CINEMAID VARCHAR2(2000), /* 영화관ID */
	SCREENID VARCHAR2(2000), /* 스크린ID */
	MOVIECD NUMBER /* 영화코드 */
);

ALTER TABLE MOVIETIME
	ADD
		CONSTRAINT PK_MOVIETIME
		PRIMARY KEY (
			TIMENO
		);

/* 영화관 */
CREATE TABLE CINEMA (
	CINEMAID VARCHAR2(2000) NOT NULL, /* 영화관ID */
	CINEMANAME VARCHAR2(2000) NOT NULL, /* 영화관이름 */
	BRAND VARCHAR2(2000), /* 브랜드 */
	LOC VARCHAR2(2000) NOT NULL /* 위치 */
);

ALTER TABLE CINEMA
	ADD
		CONSTRAINT PK_CINEMA
		PRIMARY KEY (
			CINEMAID
		);

/* 예매 */
CREATE TABLE BOOKING (
	BOOKINGNO NUMBER NOT NULL, /* 예약번호 */
	MEMBERNO NUMBER, /* 회원번호 */
	PHONENUMBER VARCHAR2(2000), /* 휴대폰번호 */
	TIMENO NUMBER NOT NULL, /* 시간번호 */
	MOVIECD NUMBER, /* 영화코드 */
	CINEMAID VARCHAR2(2000), /* 영화관ID */
	BOOKINGDATE DATE, /* 예약일 */
	SCREENID VARCHAR2(2000) /* 스크린ID */
);

ALTER TABLE BOOKING
	ADD
		CONSTRAINT PK_BOOKING
		PRIMARY KEY (
			BOOKINGNO
		);

/* 좌석 */
CREATE TABLE SEAT (
	SEATNO NUMBER NOT NULL, /* 좌석번호 */
	CINEMAID VARCHAR2(2000) NOT NULL, /* 영화관ID */
	SCREENID VARCHAR2(2000) NOT NULL, /* 스크린ID */
	SEATROW VARCHAR2(2000) NOT NULL, /* 좌석행 */
	SEATCOL NUMBER NOT NULL, /* 좌석열 */
	SEATTYPE VARCHAR2(2000) NOT NULL /* 좌석종류 */
);

ALTER TABLE SEAT
	ADD
		CONSTRAINT PK_SEAT
		PRIMARY KEY (
			SEATNO,
			CINEMAID,
			SCREENID
		);

/* 영화_영화관 */
CREATE TABLE MOVIE_CINEMA (
	MOVIECD NUMBER NOT NULL, /* 영화코드 */
	CINEMAID VARCHAR2(2000) NOT NULL, /* 영화관ID */
	SCREENID VARCHAR2(2000) NOT NULL, /* 스크린ID */
	ISRUN VARCHAR2(2000) /* 상영상태 */
);

ALTER TABLE MOVIE_CINEMA
	ADD
		CONSTRAINT PK_MOVIE_CINEMA
		PRIMARY KEY (
			MOVIECD,
			CINEMAID,
			SCREENID
		);

/* 스크린 */
CREATE TABLE SCREEN (
	CINEMAID VARCHAR2(2000) NOT NULL, /* 영화관ID */
	SCREENID VARCHAR2(2000) NOT NULL /* 스크린ID */
);

ALTER TABLE SCREEN
	ADD
		CONSTRAINT PK_SCREEN
		PRIMARY KEY (
			CINEMAID,
			SCREENID
		);

/* 예매_좌석 */
CREATE TABLE BOOKING_SEAT (
	BOOKINGNO NUMBER NOT NULL, /* 예약번호 */
	SEATNO NUMBER NOT NULL, /* 좌석번호 */
	CINEMAID VARCHAR2(2000) NOT NULL, /* 영화관ID */
	SCREENID VARCHAR2(2000) NOT NULL /* 스크린ID */
);

ALTER TABLE BOOKING_SEAT
	ADD
		CONSTRAINT PK_BOOKING_SEAT
		PRIMARY KEY (
			BOOKINGNO,
			SEATNO,
			CINEMAID,
			SCREENID
		);

/* 게시판 */
CREATE TABLE BOARD (
	AID NUMBER NOT NULL, /* 글ID */
	RID NUMBER, /* 글번호 */
	DBSUBJECT VARCHAR2(2000), /* 주제 */
	DBNAME VARCHAR2(2000), /* 글쓴이 */
	DBDATE DATE, /* 올린날짜 */
	DBMAIL VARCHAR2(2000), /* 메일 */
	DBHOMEPAGE VARCHAR2(2000), /* 홈페이지 */
	DBHITS NUMBER, /* 조회수 */
	DBMEMO VARCHAR2(2000), /* 글내용 */
	MEMBERNO NUMBER /* 회원번호 */
);

ALTER TABLE BOARD
	ADD
		CONSTRAINT PK_BOARD
		PRIMARY KEY (
			AID
		);

ALTER TABLE RATING
	ADD
		CONSTRAINT FK_MOVIE_TO_RATING
		FOREIGN KEY (
			MOVIECD
		)
		REFERENCES MOVIE (
			MOVIECD
		);

ALTER TABLE RATING
	ADD
		CONSTRAINT FK_MEMBER_TO_RATING
		FOREIGN KEY (
			MEMBERNO
		)
		REFERENCES MEMBER (
			MEMBERNO
		);

ALTER TABLE GENRE
	ADD
		CONSTRAINT FK_MOVIE_TO_GENRE
		FOREIGN KEY (
			MOVIECD
		)
		REFERENCES MOVIE (
			MOVIECD
		);

ALTER TABLE MOVIETIME
	ADD
		CONSTRAINT FK_SCREEN_TO_MOVIETIME
		FOREIGN KEY (
			CINEMAID,
			SCREENID
		)
		REFERENCES SCREEN (
			CINEMAID,
			SCREENID
		);

ALTER TABLE MOVIETIME
	ADD
		CONSTRAINT FK_MOVIE_CINEMA_TO_MOVIETIME
		FOREIGN KEY (
			MOVIECD,
			CINEMAID,
			SCREENID
		)
		REFERENCES MOVIE_CINEMA (
			MOVIECD,
			CINEMAID,
			SCREENID
		);

ALTER TABLE BOOKING
	ADD
		CONSTRAINT FK_MEMBER_TO_BOOKING
		FOREIGN KEY (
			MEMBERNO
		)
		REFERENCES MEMBER (
			MEMBERNO
		);

ALTER TABLE BOOKING
	ADD
		CONSTRAINT FK_NONMEMBER_TO_BOOKING
		FOREIGN KEY (
			PHONENUMBER
		)
		REFERENCES NONMEMBER (
			PHONENUMBER
		);

ALTER TABLE BOOKING
	ADD
		CONSTRAINT FK_MOVIETIME_TO_BOOKING
		FOREIGN KEY (
			TIMENO
		)
		REFERENCES MOVIETIME (
			TIMENO
		);

ALTER TABLE BOOKING
	ADD
		CONSTRAINT FK_MOVIE_CINEMA_TO_BOOKING
		FOREIGN KEY (
			MOVIECD,
			CINEMAID,
			SCREENID
		)
		REFERENCES MOVIE_CINEMA (
			MOVIECD,
			CINEMAID,
			SCREENID
		);

ALTER TABLE SEAT
	ADD
		CONSTRAINT FK_SCREEN_TO_SEAT
		FOREIGN KEY (
			CINEMAID,
			SCREENID
		)
		REFERENCES SCREEN (
			CINEMAID,
			SCREENID
		);

ALTER TABLE MOVIE_CINEMA
	ADD
		CONSTRAINT FK_MOVIE_TO_MOVIE_CINEMA
		FOREIGN KEY (
			MOVIECD
		)
		REFERENCES BIGDATA4.MOVIE (
			MOVIECD
		);

ALTER TABLE MOVIE_CINEMA
	ADD
		CONSTRAINT FK_SCREEN_TO_MOVIE_CINEMA
		FOREIGN KEY (
			CINEMAID,
			SCREENID
		)
		REFERENCES SCREEN (
			CINEMAID,
			SCREENID
		);

ALTER TABLE SCREEN
	ADD
		CONSTRAINT FK_CINEMA_TO_SCREEN
		FOREIGN KEY (
			CINEMAID
		)
		REFERENCES CINEMA (
			CINEMAID
		);

ALTER TABLE BOOKING_SEAT
	ADD
		CONSTRAINT FK_BOOKING_TO_BOOKING_SEAT
		FOREIGN KEY (
			BOOKINGNO
		)
		REFERENCES BOOKING (
			BOOKINGNO
		);

ALTER TABLE BOOKING_SEAT
	ADD
		CONSTRAINT FK_SEAT_TO_BOOKING_SEAT
		FOREIGN KEY (
			SEATNO,
			CINEMAID,
			SCREENID
		)
		REFERENCES SEAT (
			SEATNO,
			CINEMAID,
			SCREENID
		);

ALTER TABLE BOARD
	ADD
		CONSTRAINT FK_MEMBER_TO_BOARD
		FOREIGN KEY (
			MEMBERNO
		)
		REFERENCES MEMBER (
			MEMBERNO
		);